const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
let template = fs.readFileSync(0, 'utf8');
const data = JSON.parse(template.match(/const data = (.*);\n/)[1]);
const status = data.statuses[0];
data.column_settings = {[status]: {sort: 'due'}};
data.users = ['anna@example.com'];
data.tasks = [{id: 'task-a', title: 'Review drawing', project: 'Project text must be hidden', project_id: 'PRJ-001', status, due: '2026-10-01', responsible_emails: data.users, description: 'Review the dimensions.', attachments: [], attachment_links: [], labels: []}];
template = template.replace(/const data = .*;\n/, () => `const data = ${JSON.stringify(data)};\n`);
const messages = [];
const dom = new JSDOM(template, {runScripts: 'dangerously', url: 'http://localhost', beforeParse(window) { window.postMessage = message => messages.push(message); }});
const w = dom.window, d = w.document;
const ack = ok => w.dispatchEvent(new w.MessageEvent('message', {source: w, data: {type: 'planner:save-result', result: {event_id: messages.at(-1).value.event_id, ok, error: ok ? '' : 'Disk full'}}}));
try {
  const card = d.querySelector('.task-card');
  assert.equal(card.textContent.includes('Project text must be hidden'), false);
  assert.equal(card.textContent.includes('PRJ-001'), false);
  assert.equal(d.querySelector('.task-project-line'), null);
  assert.equal(w.getComputedStyle(d.body).backgroundColor, 'rgb(193, 254, 172)');
  assert.equal(d.querySelectorAll('.column-actions-button').length, data.statuses.length);
  const button = d.querySelector('.column-actions-button');
  button.click();
  const menu = d.getElementById('column-actions-menu');
  assert.equal(menu.hidden, false);
  assert.equal(button.getAttribute('aria-expanded'), 'true');
  assert.equal(menu.querySelector('[data-sort="due"]').getAttribute('aria-pressed'), 'true');
  menu.querySelector('[data-sort="responsible"]').click();
  assert.equal(messages.at(-1).value.action, 'sort_column');
  assert.equal(messages.at(-1).value.status, status);
  assert.equal(messages.at(-1).value.sort_by, 'responsible');
  ack(false);
  assert.match(menu.querySelector('[role=alert]').textContent, /Disk full/);
  assert.equal(menu.querySelector('[data-sort="label"]').disabled, false);
  menu.querySelector('[data-sort="label"]').click();
  assert.equal(messages.at(-1).value.sort_by, 'label');
  ack(true);
  assert.equal(menu.hidden, true);
  button.click();
  menu.dispatchEvent(new w.KeyboardEvent('keydown', {key: 'Escape', bubbles: true}));
  assert.equal(menu.hidden, true);
  assert.equal(d.activeElement, button);
  const drag = new w.Event('dragstart', {bubbles: true, cancelable: true});
  button.dispatchEvent(drag);
  assert.equal(drag.defaultPrevented, true);
  button.click();
  menu.querySelector('.archive-column').click();
  assert.equal(messages.at(-1).value.action, 'archive_column');
  assert.equal(messages.at(-1).value.status, status);
  ack(false);
  assert.match(menu.textContent, /Disk full/);
  menu.querySelector('.archive-column').click();
  ack(true);
  assert.equal(menu.hidden, true);
  w.openEditModal('task-a');
  assert.notEqual(w.getComputedStyle(d.getElementById('edit-archive')).display, 'none');
  const metadata = JSON.stringify({checklist: [{text: 'Review', done: false}], comments: [{message: 'Keep this comment'}], activity: [], due_history: []});
  w.localStorage.setItem('ewm-task-meta:task-a', metadata);
  d.getElementById('edit-archive').click();
  assert.equal(messages.at(-1).value.action, 'archive_task');
  assert.equal(messages.at(-1).value.task_id, 'task-a');
  ack(false);
  assert(d.getElementById('edit-modal').classList.contains('open'));
  assert.match(d.getElementById('edit-save-error').textContent, /Disk full/);
  d.getElementById('edit-archive').click();
  ack(true);
  assert.equal(d.getElementById('edit-modal').classList.contains('open'), false);
  assert.equal(w.localStorage.getItem('ewm-task-meta:task-a'), metadata);
  w.openNewTask(status);
  assert.equal(w.getComputedStyle(d.getElementById('edit-archive')).display, 'none');
  console.log('PASS: green theme, no card project information, column menu sorting/archive actions, retry and keyboard controls, archived ticket event, retained local metadata, and hidden archive action on new tasks.');
} finally { w.close(); }
